server:
  port: 8085 # Puerto en el que se ejecutará la aplicación
  url: ${SERVER_URL:http://localhost:8085}  # Valor por defecto si SERVER_URL no está configurado

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=model;encrypt=true;trustServerCertificate=true  ## Cambiar "model" por tu base de datos
    username: sa          ## Cambiar por tu usuario
    password: Admin12345          ## Cambiar por tu contraseña
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update  # Puede ser 'create', 'update', 'validate' o 'none'
    show-sql: false  # Puede true o false, para ver las consultas SQL en consola

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html # Ruta para acceder a Swagger UI: http://localhost:8085/swagger-ui.html
